### ISSUE TITLE
Unable to load resources in a fat jar

### ISSUE THREAD

**Issue by atomsfat** [gextech/marathon-runner#24]
When using the marathon-runner in a spring boot application it fails to load when the app it package using:

gradle bootRepackage

```groovy
Caused by: java.lang.NullPointerException
	at java.io.Reader.<init>(Reader.java:78)
	at java.io.InputStreamReader.<init>(InputStreamReader.java:72)
	at gex.marathon.core.MarathonCoreEngine$_loadDefault_closure1.doCall(MarathonCoreEngine.groovy:33)
	at gex.marathon.core.MarathonCoreEngine$_loadDefault_closure1.call(MarathonCoreEngine.groovy)
```

**Comment by atomsfat** [comment]
Solved in https://github.com/gextech/marathon-runner/pull/25
